stages:
 - build
 - test
 - install
job1:
  stage: build
  tags:
    - global
  script:
    - echo 'my build job'
job2:
  stage: test
  tags:
    - global
  script:
    - echo 'my .test1 job'
job3:
  stage: test
  tags:
    - global
  script:
    - echo 'my .test2 job'
job4:
  stage: install
  tags:
    - global
  script:
    - echo 'my install job'
