app:
  id: likeit-import-server

spring:
  application:
    name: likeit-import-server

  datasource:
    likeit:
      username: root
      password: likeit
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://82.157.160.66:3306/likeit?useUnicode=true&characterEncoding=utf8&autoReconnect=true

logging:
  level:
    com.likeit.importer.dao.repository.likeit: info

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl